-- SHOW DATABASES;

-- USE windykacja;

-- SHOW TABLES;

-- CREATE TABLE documents_actions
-- (
--     id_documents_actions INT AUTO_INCREMENT PRIMARY KEY,
--     NUMER_FV VARCHAR(45),
--     DZIALANIA VARCHAR(45),
--     JAKA_KANCELARIA VARCHAR(45),
--     KOMENTARZ_KANCELARIA_BECARED VARCHAR(500),
--     KWOTA_WINDYKOWANA_BECARED DECIMAL(10,2),
--     NUMER_SPRAWY_BECARED VARCHAR(45),
--     POBRANO_VAT VARCHAR(45),
--     STATUS_SPRAWY_KANCELARIA VARCHAR(45),
--     STATUS_SPRAWY_WINDYKACJA VARCHAR(45),
--     ZAZNACZ_KONTRAHENTA VARCHAR(10),
--     UWAGI_ASYSTENT JSON
-- )